### ISSUE TITLE
Customizing Clients

### ISSUE THREAD

**Issue by RayZick** [IdentityServer/IdentityServer3.Admin.EntityFramework#18]
Is it possible to add columns to the Clients table to store additional data (similar to what you can do to the UserAccounts table in IdentityServer using generics)?  If not, is that a change that you would see as good for the product?

Thanks

**Comment by iBoonz** [comment]
Hi,

There is a difference between customizing the user table, and the clients table.

The user can be extended with customized info, without having any effect on the behaviour of the authentication, extending the client table can have other effects. 
If you want to add custom info about your clients, I recommend to create a secured API with custom info per client, instead of changing the client table.
